### ISSUE TITLE
Display of inputs and outputs of opportunities

### ISSUE THREAD

**Issue by Ranf16** [holalluis/ecam#25]
1. The label for [wsd_KPI_water_losses](http://wacclim.org/ecam/variable.php?id=wsd_KPI_water_losses) should be **Pumping** and not Opportunities. See below. 
![kpi_waterlosses](https://user-images.githubusercontent.com/33861734/33728427-a7148908-db7a-11e7-9878-b5ff81e61d3e.PNG)

2. Inputs and outputs for opportunities should always be at the end of the table. There is also the request if they could be shown in a different shade as the color of the other inputs and outputs.
- Water abstraction
![order of inputs_ws_abstraction](https://user-images.githubusercontent.com/33861734/33728484-da748e42-db7a-11e7-9ea2-7908efd9c6cd.PNG)
![order _wsa](https://user-images.githubusercontent.com/33861734/33728616-4448dfa8-db7b-11e7-9011-9470fa8d59d4.PNG)

**Comment by holalluis** [comment]
done. thank you

**Comment by holalluis** [comment]
I'll send an email when I update the server
