### ISSUE TITLE
The license description on gitHub needs to be updated

### ISSUE THREAD

**Issue by Ranf16** [holalluis/ecam#30]
On the ECAM landing page the mentioned license is: 

ECAM by IWA and GIZ, implemented by ICRA for WaCCliM Project* is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/)	.

**Comment by holalluis** [comment]
fixed. I've modified the readme.md file, the license.txt file, and the link in the about.php page.
