### ISSUE TITLE
Fix formula of wsd_KPI_water_losses 

### ISSUE THREAD

**Issue by Ranf16** [holalluis/ecam#35]
@holalluis: José will follow up with the correct formula. 

There is an error in the formula for wsd_KPI_water_losses, i.e. the KPI  “Non revenue water per mains length”.  
 
The original performance benchmark is:
 
![image](https://user-images.githubusercontent.com/33861734/34159825-dd1e7cbc-e4ca-11e7-8afb-4fd746da7708.png)

 
Whereas in ECAM it is:
![image](https://user-images.githubusercontent.com/33861734/34159858-ff219a74-e4ca-11e7-9516-3b18cc94b50a.png)

**Comment by holalluis** [comment]
fixed
